### ISSUE TITLE
Database initialization

### ISSUE THREAD

**Issue by ecanuto** [noverde/serpens#3]
Implement init_database (or a better name).

Don't forget to include it on setup:

```python
def setup():
    load_env()
    init_logger()
    if not _SENTRY_SDK_MISSING_DEPS:
        init_sentry()
    if not _DATABASE_SDK_MISSING_DEPS:
       init_database()
```

**Comment by JoaoVitorStein** [comment]
Resolved with cc67c2ad66ca26e9e246bfe4b668ac8297ddf1fe and 5c3e6f3a845fadc9c8a4459bbfa981f2a673f3b7
