### ISSUE TITLE
Schema Validação Email

### ISSUE THREAD

**Issue by welligtonoliveira** [noverde/serpens#81]
Pegamos um caso de um email invalido que não foi pego na função validate_email  do validators.py
o email é: angelina.@gmail.com

Um teste pegando apenas com esse cenário com o tutorial abaixo esse erro foi tratado, talvez possa ajudar ...

[Tutorial Exemplo](https://stackabuse.com/python-validate-email-address-with-regular-expressions-regex/)

@gabriel-f-santos @feliperails  psc !

**Comment by julianolf** [comment]
@welligtonoliveira, eu fiz um teste com o email de exemplo que você passou e a função disse que é inválido.
```python
>>> from serpens import validators
>>> email = 'angelina.@gmail.com'
>>> validators.validate_email(email)
False
>>>
```
Consegue dar mais algum detalhe do contexto em que a função retornou verdadeiro? As versões tanto do interpretador Python quanto do Serpens?
